"""Add extraction_jobs table

Revision ID: 30fea49a7f15
Revises: 93b2a201b1a4
Create Date: 2026-04-13 17:06:33.358739
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '30fea49a7f15'
down_revision: Union[str, None] = '93b2a201b1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geocoded_coords'), table_name='geocoded_locations')
    op.drop_table('geocoded_locations')
    op.drop_index(op.f('ix_charging_sessions_user_vehicle_id_actual_cost'), table_name='charging_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_charging_sessions_user_vehicle_id_actual_cost'), 'charging_sessions', ['user_vehicle_id', 'actual_cost_eur', 'energy_kwh'], unique=False)
    op.create_table('geocoded_locations',
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('latitude', 'longitude', name=op.f('geocoded_locations_pkey'))
    )
    op.create_index(op.f('ix_geocoded_coords'), 'geocoded_locations', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###
