"""remove deprecated energy_prices table

Revision ID: 469e9a141062
Revises: 72b3047949ae
Create Date: 2026-04-19 14:08:01.584606
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '469e9a141062'
down_revision: Union[str, None] = '72b3047949ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
