"""add_battery_soh_estimates_table

Revision ID: 4c5c9e5b4a60
Revises: 188402c0ab17
Create Date: 2026-04-30 14:36:39.064511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4c5c9e5b4a60'
down_revision: Union[str, None] = '188402c0ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geocoded_coords'), table_name='geocoded_locations')
    op.drop_table('geocoded_locations')
    op.drop_index(op.f('ix_charging_sessions_user_vehicle_id_actual_cost'), table_name='charging_sessions')
    op.alter_column('extraction_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extraction_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('extraction_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_charging_sessions_user_vehicle_id_actual_cost'), 'charging_sessions', ['user_vehicle_id', 'actual_cost_eur', 'energy_kwh'], unique=False)
    op.create_table('geocoded_locations',
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('latitude', 'longitude', name=op.f('geocoded_locations_pkey'))
    )
    op.create_index(op.f('ix_geocoded_coords'), 'geocoded_locations', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###
