"""add_battery_soh_estimates_table

Revision ID: 4c5c9e5b4a60
Revises: 188402c0ab17
Create Date: 2026-04-30 14:36:39.064511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4c5c9e5b4a60'
down_revision: Union[str, None] = '188402c0ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: geocoded_locations and charging_sessions tables are NOT dropped -
    # they exist in production with live data (481 and 516 rows respectively).
    # The auto-generated alembic revision incorrectly flagged them for removal.
    # Only add the calibration columns needed by the vehicle model.
    op.add_column("user_vehicles", sa.Column("charger_power_kw", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("ice_l_per_100km", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("uphill_kwh_per_100km_per_100m", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("downhill_kwh_per_100km_per_100m", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("speed_city_threshold_kmh", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("speed_highway_threshold_kmh", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("temp_cold_max_celsius", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("temp_optimal_min_celsius", sa.Float(), nullable=True))
    op.add_column("user_vehicles", sa.Column("temp_optimal_max_celsius", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: No tables were dropped on upgrade, so only drop the added columns
    op.drop_column("user_vehicles", "temp_optimal_max_celsius")
    op.drop_column("user_vehicles", "temp_optimal_min_celsius")
    op.drop_column("user_vehicles", "temp_cold_max_celsius")
    op.drop_column("user_vehicles", "speed_highway_threshold_kmh")
    op.drop_column("user_vehicles", "speed_city_threshold_kmh")
    op.drop_column("user_vehicles", "downhill_kwh_per_100km_per_100m")
    op.drop_column("user_vehicles", "uphill_kwh_per_100km_per_100m")
    op.drop_column("user_vehicles", "ice_l_per_100km")
    op.drop_column("user_vehicles", "charger_power_kw")
    # ### end Alembic commands ###
