"""Add charging settings to charging_states

Revision ID: 692fab0b6318
Revises: e3f4a5b6c7d8
Create Date: 2026-03-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692fab0b6318'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_states', sa.Column('max_charge_current_ac', sa.String(length=50), nullable=True))
    op.add_column('charging_states', sa.Column('auto_unlock_plug_when_charged', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_states', 'auto_unlock_plug_when_charged')
    op.drop_column('charging_states', 'max_charge_current_ac')
    # ### end Alembic commands ###
