"""create 4 tables for fuel prices and economics

Revision ID: 72b3047949ae
Revises: 97b836e9f7cf
Create Date: 2026-04-19 13:55:44.433941
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72b3047949ae'
down_revision: Union[str, None] = '97b836e9f7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_economics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_net_monthly_wage_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_price_kwh_eur', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('inflation_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'date', name='uq_country_economics_code_date')
    )
    op.create_index(op.f('ix_country_economics_country_code'), 'country_economics', ['country_code'], unique=False)
    op.create_index(op.f('ix_country_economics_date'), 'country_economics', ['date'], unique=False)
    op.create_index(op.f('ix_country_economics_id'), 'country_economics', ['id'], unique=False)
    op.create_table('fuel_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('price_eur_liter', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('price_usd_gallon', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('weekly_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'week_date', 'fuel_type', name='uq_fuel_price_country_date_type')
    )
    op.create_index(op.f('ix_fuel_prices_country_code'), 'fuel_prices', ['country_code'], unique=False)
    op.create_index(op.f('ix_fuel_prices_id'), 'fuel_prices', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_week_date'), 'fuel_prices', ['week_date'], unique=False)
    op.create_table('vignettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_eur', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('validity_duration', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'name', name='uq_vignette_country_name')
    )
    op.create_index(op.f('ix_vignettes_country_code'), 'vignettes', ['country_code'], unique=False)
    op.create_index(op.f('ix_vignettes_id'), 'vignettes', ['id'], unique=False)
    op.create_table('price_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuel_price_id', sa.UUID(), nullable=False),
    sa.Column('product_cost_eur', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('excise_duty_eur', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('other_taxes_eur', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vat_eur', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tax_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fuel_price_id'], ['fuel_prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_price_id')
    )
    op.create_index(op.f('ix_price_breakdowns_id'), 'price_breakdowns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_breakdowns_id'), table_name='price_breakdowns')
    op.drop_table('price_breakdowns')
    op.drop_index(op.f('ix_vignettes_id'), table_name='vignettes')
    op.drop_index(op.f('ix_vignettes_country_code'), table_name='vignettes')
    op.drop_table('vignettes')
    op.drop_index(op.f('ix_fuel_prices_week_date'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_id'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_country_code'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    op.drop_index(op.f('ix_country_economics_id'), table_name='country_economics')
    op.drop_index(op.f('ix_country_economics_date'), table_name='country_economics')
    op.drop_index(op.f('ix_country_economics_country_code'), table_name='country_economics')
    op.drop_table('country_economics')
    # ### end Alembic commands ###
