"""add user charging plans

Revision ID: b473841e9399
Revises: e8a91c2d3f40
Create Date: 2026-09-08 16:03:29.838137

Autogenerated, then trimmed to this feature only. Unrelated model/DB drift
(AI embeddings, SoH tables, index churn) was discarded.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b473841e9399"
down_revision: Union[str, None] = "e8a91c2d3f40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_charging_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("plan_type", sa.String(length=20), nullable=False),
        sa.Column("periodicity", sa.String(length=20), nullable=True),
        sa.Column("subscription_start_date", sa.Date(), nullable=True),
        sa.Column("monthly_fee_eur", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("kwh_allotment", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("overage_price_per_kwh_eur", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("price_per_kwh_eur", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("geofence_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["geofence_id"], ["geofences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_charging_plans_geofence_id"), "user_charging_plans", ["geofence_id"], unique=False)
    op.create_index(op.f("ix_user_charging_plans_user_id"), "user_charging_plans", ["user_id"], unique=False)
    op.add_column("charging_sessions", sa.Column("charging_plan_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_charging_sessions_charging_plan_id"),
        "charging_sessions",
        ["charging_plan_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_charging_sessions_charging_plan_id",
        "charging_sessions",
        "user_charging_plans",
        ["charging_plan_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "users",
        sa.Column("default_currency", sa.String(length=3), server_default="EUR", nullable=False),
    )


def downgrade() -> None:
    op.drop_column("users", "default_currency")
    op.drop_constraint("fk_charging_sessions_charging_plan_id", "charging_sessions", type_="foreignkey")
    op.drop_index(op.f("ix_charging_sessions_charging_plan_id"), table_name="charging_sessions")
    op.drop_column("charging_sessions", "charging_plan_id")
    op.drop_index(op.f("ix_user_charging_plans_user_id"), table_name="user_charging_plans")
    op.drop_index(op.f("ix_user_charging_plans_geofence_id"), table_name="user_charging_plans")
    op.drop_table("user_charging_plans")
