"""Add iVDrive v2 Analytics fields

Revision ID: d6654a36dab7
Revises: 005_add_warning_lights
Create Date: 2026-02-25 06:16:55.313196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd6654a36dab7'
down_revision: Union[str, None] = '005_add_warning_lights'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('base_cost_eur', sa.Float(), nullable=True))
    op.add_column('charging_sessions', sa.Column('actual_cost_eur', sa.Float(), nullable=True))
    op.add_column('charging_sessions', sa.Column('provider_name', sa.String(length=100), nullable=True))
    op.add_column('charging_sessions', sa.Column('avg_temp_celsius', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('start_soc', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('end_soc', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('kwh_consumed', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('avg_temp_celsius', sa.Float(), nullable=True))
    op.add_column('vehicle_positions', sa.Column('elevation_m', sa.Float(), nullable=True))
    op.add_column('vehicle_positions', sa.Column('outside_temp_celsius', sa.Float(), nullable=True))
    op.add_column('vehicle_positions', sa.Column('weather_condition', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_positions', 'weather_condition')
    op.drop_column('vehicle_positions', 'outside_temp_celsius')
    op.drop_column('vehicle_positions', 'elevation_m')
    op.drop_column('trips', 'avg_temp_celsius')
    op.drop_column('trips', 'kwh_consumed')
    op.drop_column('trips', 'end_soc')
    op.drop_column('trips', 'start_soc')
    op.drop_column('trips', 'distance_km')
    op.drop_column('charging_sessions', 'avg_temp_celsius')
    op.drop_column('charging_sessions', 'provider_name')
    op.drop_column('charging_sessions', 'actual_cost_eur')
    op.drop_column('charging_sessions', 'base_cost_eur')
    # ### end Alembic commands ###
