"""add_battery_soh_estimates_table_v2

Revision ID: f36d25e55dd8
Revises: d4cb158bda0c
Create Date: 2026-04-30 14:39:41.555654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f36d25e55dd8'
down_revision: Union[str, None] = 'd4cb158bda0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
